apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster
  labels:
    app: prometheus-operator-prometheus
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus-operator-159334-prometheus
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster-grafana
  labels:
    app: prometheus-operator-prometheus
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-operator-1593345689
    app.kubernetes.io/name: grafana
  type: LoadBalancer  
  
   