apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis-ha
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app: redis-ha
  type: LoadBalancer
  
  
   